{% set name = "FigureGenerator" %}
{% set version = "0.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 47833dd207cdcd3a7745400b2f107e0db0de34115a061d207ccefab024dd0731

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - black
    - coverage
    - ipywidgets
    - numpy >=1.19.2
    - psutil
    - pytest
    - python >={{ python_min }}
    - simpleitk !=2.0.*,!=2.2.1

test:
  imports:
    - FigureGenerator
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/FigureGenerator/
  summary: Making screenshots for presentations and manuscripts.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
