{% set name = "FigureGenerator" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FigureGenerator-{{ version }}.tar.gz
  sha256: 52e6436d88fbc550dbc6724e8f3b512fad547cfa6d72bc7d321b966c6302c79b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - black
    - coverage
    - ipywidgets
    - numpy >=1.19.2
    - psutil
    - pytest
    - python >=3.6
    - simpleitk !=2.0.*,!=2.2.1

test:
  imports:
    - FigureGenerator
  requires:
    - pip

about:
  home: https://pypi.org/project/FigureGenerator/
  summary: Making screenshots for presentations and manuscripts.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
