{% set name = "FigureGenerator" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/FigureGenerator-{{ version }}.tar.gz
  sha256: 96322e6a616d5697bd8ae1ab080d1cb4b3a4bb4720ce6343f576d37b74d1ac4d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - black
    - coverage
    - ipywidgets
    - numpy >=1.19.2
    - psutil
    - pytest
    - python >={{ python_min }}
    - simpleitk !=2.0.*,!=2.2.1

test:
  imports:
    - FigureGenerator
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/FigureGenerator/
  summary: Making screenshots for presentations and manuscripts.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
